volumes:
    postgreas-data:
        external: true
services:
    postgres:
        image: postgres:14.5-bullseye
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: samplehub
            POSTGRES_USER: samplehub
            POSTGRES_DB: samplehub
        ports:
            - 15432:5432
    # db:
    #     image: postgres:14.2-bullseye
    #     volumes:
    #         - database_volume:/var/lib/postgresql/data
    #     environment:
    #         - POSTGRES_DB=samplehub
    #         - POSTGRES_USER=samplehub
    #         - POSTGRES_PASSWORD=samplehub
    #     ports:
    #         - 15432:5432

    fastapi:
        environment:
            SIGNING_KEY: 396230372c74024966c9e20cb48f0b806f0fa682e5f5557c243f3f74e98c6749
            DATABASE_URL: postgresql://samplehub:samplehub@postgres/samplehub
            CORS_HOST: http://localhost:5173
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        environment:
            VITE_API_HOST: http://localhost:8000
            BASE_URL: http://localhost:5173
        ports:
            - "5173:5173"
